name: Odoo
on:
  push:
    branches:
      - master
    paths:
      - salt/odoo/**
      - docker/odoo/**
      - .github/workflows/odoo.yml

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - name: Build and push odoo 14
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/odoo/Dockerfile
          push: true
          tags: ${{ github.repository_owner }}/odoo:14
          build-args: ODOO_VERSION=14
      - name: Build and push odoo 15
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/odoo/Dockerfile
          push: true
          tags: ${{ github.repository_owner }}/odoo:15
          build-args: ODOO_VERSION=15
      - name: Build and push odoo 13
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/odoo/Dockerfile
          push: true
          tags: ${{ github.repository_owner }}/odoo:13
          build-args: ODOO_VERSION=13
      - name: Build and push odoo 12
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/odoo/Dockerfile
          push: true
          tags: ${{ github.repository_owner }}/odoo:12
          build-args: ODOO_VERSION=12
      - name: Build and push odoo 11
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/odoo/Dockerfile
          push: true
          tags: ${{ github.repository_owner }}/odoo:11
          build-args: ODOO_VERSION=11
