name: PBX
on:
  push:
    branches:
      - master
    paths:
      - salt/asterisk/**
      - salt/agent/**
      - docker/asterisk/**
      - docker/agent/**
      - .github/workflows/pbx.yml

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ github.repository_owner }}/pbx:1.0
            ${{ github.repository_owner }}/pbx:latest
